// Generated by test/dev/sound-eval/tiny/make_config.py from calibrate.py. Do not edit by hand.
// Class order = the model's output order after the background score (scores[1 + i]).
#include "sound_events.h"

static const se_class_cfg_t SOUND_EVENT_CONFIG[] = {
    {"alarm", 0.85f, 0.75f, 2, 30, 0, 1},  /* unseen check: 1/32 found, 1.0 false/h */
    {"baby_crying", 0.98f, 0.88f, 1, 30, 0, 1},  /* unseen check: 9/32 found, 0.0 false/h */
    {"cough", 0.98f, 0.88f, 2, 30, 0, 0},  /* unseen check: 9/32 found, 0.5 false/h */
    {"dog_bark", 0.70f, 0.60f, 3, 30, 0, 0},  /* unseen check: 21/32 found, 0.0 false/h */
    {"door_slam", 0.95f, 0.85f, 2, 30, 0, 0},  /* unseen check: 0/32 found, 0.0 false/h */
    {"doorbell", 0.85f, 0.75f, 3, 30, 0, 0},  /* unseen check: 1/32 found, 1.0 false/h */
    {"glass_breaking", 0.90f, 0.80f, 2, 30, 0, 1},  /* unseen check: 12/32 found, 3.51 false/h */
    {"gunshot", 0.95f, 0.85f, 3, 30, 0, 1},  /* unseen check: 3/32 found, 0.0 false/h */
    {"knock", 0.90f, 0.80f, 3, 30, 0, 0},  /* unseen check: 9/32 found, 3.51 false/h */
    {"microwave", 0.80f, 0.70f, 3, 30, 0, 0},  /* unseen check: 3/32 found, 0.5 false/h */
    {"phone_ring", 0.95f, 0.85f, 3, 30, 0, 0},  /* unseen check: 1/32 found, 1.0 false/h */
    {"scream", 0.99f, 0.89f, 2, 30, 0, 1},  /* unseen check: 0/32 found, 2.5 false/h */
    {"siren", 0.97f, 0.87f, 1, 30, 0, 0},  /* unseen check: 15/32 found, 2.0 false/h */
    {"toilet_flush", 0.97f, 0.87f, 1, 30, 0, 0},  /* unseen check: 17/32 found, 0.5 false/h */
    {"water_running", 0.97f, 0.87f, 3, 30, 600, 0},  /* unseen check: 1/32 found, 0.0 false/h */
};
#define SOUND_EVENT_CLASSES 15
